#
# Service to perform raycasting for several virtual viewpoint poses
#

# Time at which to fetch the ROS transforms
time stamp

# Array of viewpoint poses in camera frame
geometry_msgs/PoseArray pose_array

# Number of pixels of the camera in height
int32 n_pxl_height

# Number of pixels of the camera in width
int32 n_pxl_width

---

# Whether the call was successful
bool is_success

# Raycasting results for each viewpoint pose (in camera frame)
CameraOutput[] results
