#
# Service to update a Gaussian Process for several sets of camera measurements
#

# Whether to update the mean
bool update_mean

# Mean of the Gaussian Process
float32[] mean

# Whether to use the internal GP mean instead
bool use_internal_mean

# Covariance of the Gaussian Process
mf_common/Float32Array[] cov

# Whether to use the internal GP covariance instead
bool use_internal_cov

# Sets of camera measurements (in global camera frame)
mf_sensors_simulator/CameraOutput[] meas

# Whether to return the new covariances diagonal, or the full covariances
bool return_cov_diag

# Whether to evaluate the Gaussian Process at the measured points
bool eval_gp

---

# Updated means (one for each set of measurements)
mf_common/Float32Array[] new_mean

# Updated covariances (one for each set of measurements)
mf_common/Array2D[] new_cov

# Updated covariances (one for each set of measurements)
mf_common/Float32Array[] new_cov_diag

# Values of the evaluated Gaussian Process
mf_common/Float32Array[] eval_values
